### ISSUE TITLE
Prognosis? 

### ISSUE THREAD

**Issue by loganpowell** [supabase/doctest-js#2]
Great that you're picking this up! Just curious about your experience with the code base so far...

**Comment by kiwicopple** [comment]
Hey @loganpowell sorry I completely missed your issue in my notifications. 

There are a few bugs that I need to look into, especially around asserting objects. Also I will try figure out if we can use this for class functions. 

Overall it's great though - you can see that we are using it in our [postgrest-js test](https://github.com/supabase/postgrest-js/blob/master/test/unit/Doctests.test.js).

Let us know if you have any other features/improvements in mind! I'll let you close this once you're read it

**Comment by loganpowell** [comment]
Great news! I'll give it a go 👍
